### ISSUE TITLE
Bot Request

### ISSUE THREAD

**Issue by HyperfireRS** [Discord-Utilities/Discord-Utilities#2]
### Welcome! Please fill out these questions carefully.

**Discord Username and ID**
name#1234 712379278731273

**Bot Name**
Discord Utilities

**Bot Profile picture**
link to pfp

**Bot About me**
I am a robot.

# Bot Uses
**What is the invite link to the server you plan on adding the bot to?**
discord.gg/123

**What is your appeals link?**
appeal.com

**Do you agree to the rules?**
mhm

**Comment by aidaner** [comment]
hi

**Comment by PlanetDude** [comment]
lmao what is this

**Comment by aidaner** [comment]
Idk
