### ISSUE TITLE
Bot request I guess

### ISSUE THREAD

**Issue by aidaner** [Discord-Utilities/Discord-Utilities#6]
### Welcome! Please fill out these questions carefully.

**Discord Username and ID**
AidanER1#7222

**Bot Name**
Bot

**Bot Profile picture**
blank lol

**Bot About me**
A bot made by hyper I guess

# Bot Uses
**What is the invite link to the server you plan on adding the bot to?**

https://discord.gg/yQzJAmRvXX

**What is your appeals link?**
I have none 

**Do you agree to the rules?**

Yes

**Comment by HyperfireRS** [comment]
denied, sorry

**Comment by aidaner** [comment]
ok
